# Generated by Django 3.0.5 on 2020-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
