# Generated by Django 3.0.5 on 2020-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20200417_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
